a = ["Python", "Exception", "Try and except"]

try:
    for i in range(4):
        print("The index and element from the array is", i,a[i])
except:
    print("index out of range")
    